### ISSUE TITLE
support iframe

### ISSUE THREAD

**Issue by Pistil-Studio** [saribe/eModal#10]
Hi, il would be usefull if your script could open remote adress in an iframe.

**Comment by saribe** [comment]
Hi,

The eModal has the pleasure to release the support to iframes

please try i!


you can use it as the other functions:

eModal.iframe(url, title, callback)

the callback is called when the iframe is loaded, and it get as parameter
the iframe dom element.

the support page hasn't details about the iframe..

we will deploy informaions asap



*Samuel Ribeiro Pinto*


2015-06-29 13:49 GMT+01:00 Frumillon Pierre <notifications@github.com>:

**Comment by Pistil-Studio** [comment]
thx a lot !
