### ISSUE TITLE
Malformed HTML

### ISSUE THREAD

**Issue by rbista** [saribe/eModal#11]
A malformed div tag shows up in the bottom of the modal during the loading:

you should replace this (line 151):
```
.replace('>1<', defaultSettings.loadingHtml);
```
with this :

```
.replace('>1<', '>'+defaultSettings.loadingHtml+'<');
```

in order to close div tag.

**Comment by saribe** [comment]
Hi rbista,
That's right,

thanks for the feedback!

I will fix it and update build ASAP.

**Comment by saribe** [comment]
Hi rbista,

The fix was uploaded.

thanks.
