### ISSUE TITLE
Vertical Scrolling Option or Ability to set window size params

### ISSUE THREAD

**Issue by HarveyEV** [saribe/eModal#12]
I have a responsive page loading (bootstrap), but the content is overflowing the modal window instead of wrapping. The page content resizes properly in the native browser window so I know it's not a page layout issue unless the "lg" size just happens to be sitting between default media breakpoints. 

Any suggestions? Maybe a custon size param would be nifty. 

Thanks.

**Comment by saribe** [comment]
can you please provide an example in codepen or some other javascript
online editor?
That would be great.


*Samuel Ribeiro Pinto*


2015-07-17 0:12 GMT+01:00 Mike Harvey <notifications@github.com>:

**Comment by HarveyEV** [comment]
Nevermind. I reformatted the source. All good.

**Comment by saribe** [comment]
What you were saing is if:

eModal.alert("VeryLongText...dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")


the text overflows?...

Try version 1.1.03
