### ISSUE TITLE
iFame problem

### ISSUE THREAD

**Issue by theprimstore** [saribe/eModal#16]
Hi

i try click on demo iframe have problem loading not hide

**Comment by theprimstore** [comment]
Fix it on line 417

```
function iframeReady() {
    $(this)
        .parent()
        .find('div' + tmpModalContent)
        .fadeOut(function () {
            $(this).remove();
        });

    return execute();
}
```
replace with

```
function iframeReady() {
    $(this)
        .parent()
        .find('div.modal-body')
        .fadeOut(function () {
            $(this).remove();
        });

    return execute();
}
```

**Comment by saribe** [comment]
Replaced by:

function iframeReady() {
    $(this)
        .parent()
        .find('div.' + tmpModalContent)
        .fadeOut(function () {
            $(this).remove();
        });

    return execute();
}

Thanks.
