### ISSUE TITLE
Using options var => Clicking 'Cancel' closes after 2nd click (not first)

### ISSUE THREAD

**Issue by smartey** [saribe/eModal#18]
VERSION 1.1.X

When using a an 'options' var like the one below, clicking cancel in the dialog window doesn't respond the first time but the second click it does closing the dialog.

Code used in php:
var options = {
        message: "The famouse question?",
        title: 'Header title',
        size: 'sm',
        subtitle: 'smaller text header',
        label: "True",
	function(result) { result ? DoSomething : ' ' }
 };

Actual call (javascript): eModal.confirm(options);

Regards,
Eric

**Comment by saribe** [comment]
Hi Eric!

I can see some issues in you code!

1# if version <= 1.1.x
   Your options is miss constructed!
   
    var options = {
      message: 'The famous question?',
      title: 'Header title',
      size: eModal.size.sm,
      subtitle: 'smaller text header',
      label: "True",
      callback: function(result) { if(result){ DoSomething();} }
    };

    eModal.confirm(options);


2# if version >= 1.2.x

    var options = {
      message: 'The famous question?',
      title: 'Header title',
      size: eModal.size.sm,
      subtitle: 'smaller text header',
      label: "True"
    };
   
    eModal
       .confirm(options)
       .then(DoSomething/*, optionalDoSomethingElseOnNegative*/ );

**Comment by smartey** [comment]
My apologies, I wasn't aware of my code 'miss' and thank you for your reply!

Regards,
Eric
