### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by Pistil-Studio** [saribe/eModal#19]
Hi,
It will be usefull if we could fixe the header or the modal. (like this : https://groups.google.com/forum/#!topic/twitter-bootstrap-stackoverflow/CTGFn30PqLI)

I dont find a solution without fork your plugin.

Thx

**Comment by saribe** [comment]
I will file a task for this feature..

thanks for the suggestion.

*Samuel Ribeiro Pinto*


2015-09-17 12:07 GMT+01:00 Frumillon Pierre <notifications@github.com>:

**Comment by Pistil-Studio** [comment]
Hi Sam, i maid a little patch to add this option.
I dont know if I maid a good patch, but it works.

I make the pull request

**Comment by saribe** [comment]
Hi, please chek my feedback, and I will merge it! 

Thanks!

**Comment by Pistil-Studio** [comment]
Hi,
I will take a look next week.
I update my code and i submit it to you 
Bye

**Comment by saribe** [comment]
Thanks!

*Samuel Ribeiro Pinto*


2015-10-09 13:57 GMT+01:00 Frumillon Pierre <notifications@github.com>:
