### ISSUE TITLE
Size problem 

### ISSUE THREAD

**Issue by snnyk** [saribe/eModal#22]
eModal.ajax({
                        url     : url,
                        title   : 'the title',
                        size    : eModal.size.xl
        });

but size all time sm

**Comment by saribe** [comment]
Hi snnyk,

I can't repro this...

Are you using the last version?

XL size only become available in V 1.2.1-rc1

Please let me know if you get any issues.

**Comment by GustavoDMS** [comment]
I have the same problem.
The modal open in xl size, but after the content is loaded, the modal auto resize to the sm size. It's only occur in xl size paramter.
