### ISSUE TITLE
form ajax errors

### ISSUE THREAD

**Issue by androidealp** [saribe/eModal#24]
Hi, 

How to insert custom code for manipulate the event emodal to close? 

My form is loaded into the emodal, if the submit form is not available, i want that the eModal not close, if is available then close emodal.

```javascript
//this code emodal ajax
buttons: [
	            {text: 'Salvar', style: 'info',   close: false, click: save },
	            {text: 'Fechar', style: 'danger', close: true}
	        ],
//this code event save
function save(){
$.ajax({
sucess:function(data){

if(data.error){
$.notify({data.error.msn});
eModal.close(false); // ????
}else{
$.notify({data.success.msn});
eModal.close(true); // ????
}

}
});
}
```

**Comment by saribe** [comment]
You can use remove "eModalclose(false);" and use eModal.close() instead "
eModalclose(true);" to close the current modal.


*Samuel Ribeiro Pinto*


2015-12-15 1:59 GMT+00:00 androidealp <notifications@github.com>:
