### ISSUE TITLE
Unknown module when trying to consume with RequireJS

### ISSUE THREAD

**Issue by atcrawford** [saribe/eModal#25]
It looks like this plugin relies on two modules, 'jquery' and 'Q'. I've never seen the module 'Q' before. Can you explain why that module is required, and how I can change my requirejs configuration to take it into account?

For what it's worth, it looks like the variable for that module is only used in one place:
```
        function _createDeferred() {
            var dfd = q ? q.defer() : $.Deferred();
            if (!q) {
                dfd.catch = dfd.fail;
                dfd.promise = dfd.promise();
            }
            dfd.promise.element = $modal;
            return dfd;
        }
```

**Comment by atcrawford** [comment]
Ah, after a little more searching, I've found what looks like the project for the module that's being referenced. From the code snippet above it seems Q might actually be optional/unnecessary, but I get the following console error in my project when I don't have it: 

```
Error: Script error for: Q
```

**Comment by saribe** [comment]
Hi Drew Crawford, sorry about the delay.

Thanks for the feedback.
I've set the Q as optional on AMD.

Should you need any further information, please do not hesitate to contact me.

**Comment by saribe** [comment]
Hello, can you confirm that this issue is resolved?

**Comment by atcrawford** [comment]
Yes, I can confirm that I'm no longer getting the error when I reference this js module without having Q included as well. Thanks for fixing this!

**Comment by saribe** [comment]
Thank you for reporting!

Best!

*Samuel Ribeiro Pinto*


2016-01-25 17:15 GMT+00:00 Drew Crawford <notifications@github.com>:
