### ISSUE TITLE
Feature suggestion :  Give an id/class to dialogue as an option.

### ISSUE THREAD

**Issue by mikecastrodemaria** [saribe/eModal#26]
Feature suggestion : add to options the ability to set an id  and or class to the dialogue.

Ex param : var params = {modalId = 'my-modal-id', modalclass = 'my-modal-class' }
Ex modal : <div id="my-modal-id" class="modal-dialogue modal-lg my-modal-class'">....</div>

It will help a lot to modify modal contextually.
Thanks

**Comment by AlphawolfWMP** [comment]
+1

**Comment by saribe** [comment]
You can access the element, do you really need the id?

```javascript
var promiseAndMore = eModal.alert('Hello Jack', 'From Madam');

promiseAndMore.element
     .find('modal-body')
     .addClass('my-very-cool-animation');
```

In the returned object from eModal execution, you get the jQuery DOM element reference.
You can do what ever you what with it.

*But by the id or class could be helpful for you?*

**Comment by saribe** [comment]
Any update on this?

Can you give me an example why should we add this feature?

**Comment by maxi032** [comment]
because sometimes we need to check if the modal is shown or hidden and do stuff based on that

**Comment by saribe** [comment]
Now it is possible to set id on eModal

`eModal.setId('your-id');`
