### ISSUE TITLE
Unrecognised expression in main.js

### ISSUE THREAD

**Issue by dageddy** [saribe/eModal#28]
Encountering this message:
Syntax error, unrecognized expression: a[href*=#]:not([href=#]) 

It refers to main.js:
$('#navbar-collapsible li')
        .on('activate.bs.scrollspy', scrollspy)
        .find('a[href*=#]:not([href=#])')
            .click(hrefClick);

I'm seeing this in IE11 on a 64-bit Win7 machine

**Comment by saribe** [comment]
Hi dageddy,

Thanks for the warning, I've updated the jQuery version and this issue is
now present.

I will fix it to $('a[href*="#"]:not([href="#"])') asap.


*Samuel Ribeiro Pinto*


2016-01-20 0:37 GMT+00:00 dageddy <notifications@github.com>:
