### ISSUE TITLE
Doesn't work on Firefox 43.0.4

### ISSUE THREAD

**Issue by mariapaulinar** [saribe/eModal#29]
I've attached screenshot to this message.
![error bs emodal](https://cloud.githubusercontent.com/assets/1920342/12514056/49e05368-c0ef-11e5-99b3-eb560970c65e.png)

**Comment by saribe** [comment]
Hi, thanks for reporting!

Fix: https://github.com/saribe/eModal/issues/28

This was an update of jQuey break :(
