### ISSUE TITLE
callback doesn't fire first time

### ISSUE THREAD

**Issue by phil-arista** [saribe/eModal#3]
Hey (great project by the way)

I'm seeing an issue where the callback only fires when I call the function the second(+) time.

Here's my code:
https://gist.github.com/fa839f059b263b9e7be9.git

Any ideas?  I noticed that when I run it the first time, my url goes from:
/static-nodes to /static-nodes?# - What's the question mark doing?

Thanks!

**Comment by saribe** [comment]
Hi Phil,

I can't access the url:
Failed to load resource: the server responded with a status of 404 (Not Found)


By your description i can assume that you are using a <a href="#" .../> tag and the click bind is not working as it should be...



Can you post here your issue or in http://codepen.io/ alike?

That will be great
Thanks

**Comment by phil-arista** [comment]
Sorry about that.  

http://codepen.io/anon/pen/bNJKPL.js

It just shows the interesting parts (the menuitem creation with has the onClick to the clone function). The clone() function includes the eModal.prompt().

**Comment by saribe** [comment]
Hi Phil,
the code is ok.

I have completed your codepen:
http://codepen.io/anon/pen/EaJpMN?editors=101

It's working, please take a look.

**Comment by phil-arista** [comment]
Thanks!
