### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by guilhermegonzaga** [saribe/eModal#33]
could provide this package via bower?
thanks for this package

**Comment by saribe** [comment]
Good idea, asap!

I will let you know!

**Comment by saribe** [comment]
However, you can use it like this:

```
 "dependencies": {
    "eModal": "https://github.com/saribe/eModal.git"
    ...
}
```

**Comment by saribe** [comment]
Hello, package 1.2.6 is available over bower, I will commit it to npm asap.

Thanks

**Comment by guilhermegonzaga** [comment]
Thank you, this will help many persons.

**Comment by ssssteve** [comment]
Is this updated on npm? It seems to be 1.1.3 on there still, and it would be great if it could be updated.
