### ISSUE TITLE
Chaining a Confirm and an Ajax modal

### ISSUE THREAD

**Issue by ssssteve** [saribe/eModal#34]
I have a site where I'm using eModal, and mostly it works fine. However, at one point I wish to delete some data, but I need confirmation first. Therefore I have a confirm eModal, which the callback set to display an Ajax emodal (syntax is for vue.js, but works OK otherwise):

```
deleteMonth: function(dateString) {
  var self = this;

  var options = {
      title:      'Delete This Months Data',
      message:    'Are you sure that you wish to delete all this months data?',
      size:       eModal.size.sm,
      label:      'Delete'
  };

  eModal.confirm(options)
      .then(function() {
    self.destroyMonth(dateString);
      }
    );
},

destroyMonth: function(dateString) {
  var self = this;

  var options = {
      url:    '/path/to/delete',
      title:  'Delete This Data',
      size:   eModal.size.sm
  };

  eModal.ajax(options);
},
```

You can see it with this [link to fiddle](https://jsfiddle.net/sssssteve/udmn5qxf/)

Is it possible to chain modals in this way? I would have thought having a confirm modal before an ajax modal would be fairly common - am I missing something?

**Comment by saribe** [comment]
Hi Steve, eModal was design as a Singleton, so if you want to have chain, that will break in animation!


as workaround, you can wait for the animation: https://jsfiddle.net/udmn5qxf/3

**Comment by ssssteve** [comment]
OK, the workaround sounds fine to me, thanks for your help
