### ISSUE TITLE
Better documentation on how to link

### ISSUE THREAD

**Issue by beruic** [saribe/eModal#38]
Serving the script through the raw link for the master branch (as you suggest in the readme) is not a good solution because this is also (presumably) the address for any future new versions. You should supply the stable release link from your release tag instead in your readme.

Using [RawGit](https://rawgit.com/) you can easily make CDN-links. I.e. supplying RawGit with [https://github.com/saribe/eModal/blob/1.2.6/dist/eModal.js](https://github.com/saribe/eModal/blob/1.2.6/dist/eModal.js) (current stable tagged version) gives you [https://cdn.rawgit.com/saribe/eModal/1.2.6/dist/eModal.js](https://cdn.rawgit.com/saribe/eModal/1.2.6/dist/eModal.js). Since there is  no uptime or support guarantees on this CDN, it may not be fully safe for production, but no CDN should be trusted fully, so users should use the link to download eModal for local serving and perhaps use the CDN link with fallback.
To make it easy for users to use CDN with fallback you could supply an expression to test whether the library has been loaded properly. Here is an example of CDN with fallback using jquery.

``` javascript
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>(window.jQuery)||document.write('<script src="/lib/jquery/script"><\/script>');</script>
```

Just switch `window.jQuery` with somthing that evaluates to `true` if eModal has been loaded correctly like so:

``` javascript
<script src="https://cdn.rawgit.com/saribe/eModal/1.2.6/dist/eModal.min.js"></script>
<script>([emodal_detection_expression])||document.write('<script src="[server_local_copy]"><\/script>');</script>
```

**Comment by saribe** [comment]
Thanks for the suggestion
