### ISSUE TITLE
Accessing iframe data

### ISSUE THREAD

**Issue by gigbuilder** [saribe/eModal#39]
I'm building a modal FORM using an iframe and a separate form html on my site.  I can load it without any problem BUT when I create a SAVE button (on the primary html page) to a function I cannot seem to get access to the form fields in the iframe.  I've even hacked the code a bit to add an ID to the iframe but still have no luck getting a handle on the iframe html document object.  Any suggestions?

**Comment by Malkafly** [comment]
need same thing

**Comment by saribe** [comment]
unless you are on the same domain or allow cross-domain-request, you may not be able to access to the iFrame DOM.
