### ISSUE TITLE
Questions: On Hidden Handler and iFrame size

### ISSUE THREAD

**Issue by samvanity** [saribe/eModal#44]
Hi,

Thanks for the wonderful plugin first. I'm using the Iframe feature and it works great so far :)

2 questions - 
1. How do I add an on hidden handler to the modal? I'd like to refresh the main page once the modal containing the iframe is closed.
2. How do I control the size of the iframe so that it doesn't auto adjust height to fit the screen (I already set size to 'lg')? I'm using the modal as a file upload window and it doesnt need to be that "tall."

Thanks !

**Comment by rkaartikeyan** [comment]
Hi did anyone got solution for the question? like Refresh main page when the Popup get closed?

**Comment by saribe** [comment]
You can and should use the bootstrap events,

take a look here http://getbootstrap.com/javascript/#modals-events

```
var $eModal = eModal.iFrame(args);

 $eModal.on('hidden.bs.modal', (e) => {
  // do something...
});
```
