### ISSUE TITLE
Prevent Modal to close when clicking outside the Modal 

### ISSUE THREAD

**Issue by Sharj** [saribe/eModal#47]
Prevent modal to close when clicking outside the modal or by pressing 'Q' on the keyboard by introducing a new option property.

The above behaviour can be achieved by adding following attributes to the main div.modal 'data-backdrop="static" data-keyboard="false" ' - It can also be archived by JS  

I introduced a new option and tried to add 'data-backdrop' in div.modal '_getMessage(data)' function but it didn't quite work yet. 
What would be the best way to add prevent-close modal?

**Comment by saribe** [comment]
You can use eModal.setModalOptions(params) to set that behaiviour.

Options can be passed via data attributes or JavaScript. For data attributes, append the option name to data-, as in data-backdrop="".

Take a look:
http://getbootstrap.com/javascript/#via-javascript
