### ISSUE TITLE
Please provide an option to set a custom ID on the modal

### ISSUE THREAD

**Issue by rgasch** [saribe/eModal#5]
This would be useful by allowing certain actions to target only specific modals.

**Comment by saribe** [comment]
Can you please provide more detail, perhaps an example?

Best,

-----Original Message-----

**Comment by saribe** [comment]
Everytime you create a eModal, this return the jQuery object, and then you can do what ever you need with it!

var $eModal = emodal.alert("Message", "Title");
$eModal.find("...").prop("Id", "some-id")...
