### ISSUE TITLE
Scrollbar on big modal

### ISSUE THREAD

**Issue by germangallo** [saribe/eModal#51]
Hi!

This is my first comment here in GitHub, so I don't know if this is the proper place.

I'm working in a project and this plugin is helping me a lot (thanks for that!).

However, I'm having the following problem: I'm mainly using the emodal to load pages via ajax. Sometimes the pages are quite long, and it's needed to scroll down to read all the content. Although it works great if the user scroll with the mouse's scroll, It quits the modal if the user clicks on the navbar of the browser.

Do you have any idea of how can I get to work the browser's navbar on big pages? 

Thank you very much and best regards
![scroll-github](https://cloud.githubusercontent.com/assets/19785987/15838277/8716ac84-2c13-11e6-8f58-92314071b2f8.jpg)

**Comment by saribe** [comment]
It V 1.2.63, the scroller will be added!
