### ISSUE TITLE
eModel Ajax success handler 

### ISSUE THREAD

**Issue by kushal555** [saribe/eModal#52]
Hi, 
first of all thank you very much for a such a good plugin.
As per my requirement i need the call back function after ajax success call. 
So can you please tel me know how can i do this.
Let me explain = > 
Actually i need the data according to `id` but if `id` is not found in that case i will return the json_resopnse false. So in that case i need to show error message inside the model.
I can see you are using `function OK(){}` inside your lib file. Actually i need to override this function because i am returning json response not html.

**Comment by saribe** [comment]
Now you can add option callbacks...

```
var options = {
        url: "/views/portview.html",
        title:'Header title',
        size: eModal.size.sm,
        subtitle: 'smaller text header',
        dataType: 'json',
        success: result => result[id],
        buttons: [
            {text: 'OK', style: 'info',   close: true, click: eventA },
            {text: 'KO', style: 'danger', close: true, click: eventB }
        ],
        ...
    };

eModal.ajax(options);
```
