### ISSUE TITLE
eModal.alert not showing the body

### ISSUE THREAD

**Issue by gsdiama** [saribe/eModal#56]
Hi everybody,

I'm very happy with eModal but I don't know why, even if I call like that:

eModal.alert(parameters.message, lang.message);

There is a case in where just the header is shown, and I have check that both parameters.message and lang.message are strings and are not empty.

I would much appreciate if you could help me.

Thanks in advance,

Gsdiama

![arriba](https://cloud.githubusercontent.com/assets/22974565/19588579/06c0b0ce-9767-11e6-9596-b86024d695a6.jpg)

**Comment by saribe** [comment]
HI, sorru about the delay, cauyou add more details?

The parameters.message and lang.message are primitive strings?

If possible provide the script that are you running with mock data, use codepen or other online editor!

**Comment by gsdiama** [comment]
Hi,

Finally, I used Bootstrap modal to solve the problem, sorry :-( Both lang.message and parameters.message were javascript strings that were fed properly. If I have the chance of trying again this part I will tell you.

Thanks again.

Yours,

GSdiama

**Comment by saribe** [comment]
Ok, thank you!

Will be glad to help...
