### ISSUE TITLE
Uncaught TypeError: e.ajax(...).success is not a function

### ISSUE THREAD

**Issue by Priyank780** [saribe/eModal#58]
return t.url && e.extend(s, t),
            e.ajax({
                url: s.url,
                dataType: "text"
            }).success(r).fail(l),

I'm using JQuery version  3.1.1.

As Jquery removed success method, you should use .done() method

**Comment by saribe** [comment]
Hi, tnx for the suggestion, please make sure you have the eModal.js v1.2.65

**Comment by Priyank780** [comment]
Thanks man for the quick fix.
