### ISSUE TITLE
Close modal on escape

### ISSUE THREAD

**Issue by rebutatul** [saribe/eModal#6]
function createModalElement() should contain 
`<div class="modal fade" tabindex="-1">`
instead of 
`<div class="modal fade">`
... or an option to add tabindex for "keyboad: true"

Thanks!

**Comment by saribe** [comment]
hi, you can set the modal options like this:
eModal.setModalOptions({ 
        keyboard: true,
        ...
    });

**Comment by rebutatul** [comment]
You're right, that's the correct method.

But the modal container should have tabindex="-1"

Thank you!

**Comment by saribe** [comment]
I Will fix it asap and let you know.
Best.

**Comment by saribe** [comment]
The ' tabindex="-1"' is supported in V1.0.1!

Thanks for feedback.
