### ISSUE TITLE
iframe with post data parameters

### ISSUE THREAD

**Issue by ghost** [saribe/eModal#61]
is there any option ???

if not it will be helpful...

something like [this](http://stackoverflow.com/questions/20353162/how-to-post-data-to-iframe-with-jquery/25545331#25545331)

btw Great work & plugin 

thanks in advance....

**Comment by saribe** [comment]
Added support here:
https://github.com/saribe/eModal/commit/12052d6e11a3e60ae2317504f0009cad6b765448


Example
eModal.iframe({
   url: 'https://www.youtube.com/embed/YRgluqis7rQ?autoplay=1', 
   title: 'Magic title', 
   data: { name: 'Santa Claus', method: 'POST' }
})
