### ISSUE TITLE
'root' is undefined

### ISSUE THREAD

**Issue by atcrawford** [saribe/eModal#63]
In our project we are using RequireJS to load our modules. After attempting to upgrade to the latest version of emodal, we started getting a javascript error that says `root is undefined`. It looks like `root` is a parameter that should be getting set by RequireJS, but there's only one item in the array of modules for RequireJS:
```
    define(['jquery'], function($, root) {
```

I'm able to run the tests for the latest version locally though and they all pass. It looks like when running in that scenario the `root` variable contains an empty javascript object. It's not clear to me why `root` isn't `undefined` when running in that scenario.

It looks like simply adding an if statement like this before setting the properties causes everything to work as expected in our project.
```
        ...
        if (!root)
            root = {};

        root.addLabel = addLabel;
        root.ajax = ajax;
        ...
```

Do you have a recommendation for how we should proceed? Is it "wrong" to include this if statement, and if not, would you like for me to submit that small change in a PR? Should we take a different approach altogether?

**Comment by brnmonteiro** [comment]
same here

**Comment by mariusz-kraj-c** [comment]
+1

**Comment by dambrogia** [comment]
+1

**Comment by Amunak** [comment]
Why do I always pick a library that gets abandoned in a year or two...

**Comment by saribe** [comment]
Added the suggestion
