### ISSUE TITLE
multi/stackable modal

### ISSUE THREAD

**Issue by ibnbay99** [saribe/eModal#65]
is this support to multi/stack-able modal.
if in bootstrap modal it doesn't support, any hack?

btw i like your plugin.
Thanks...

**Comment by saribe** [comment]
Unfortunately, eModal was not designed to open stack of modals, we believe that is not good user experience.

eModal is built as a singleton, right now there is no way to hack it.

We are planning refactor it to fully support new versions of bootstrap, and then we can rethink this scenario.
