### ISSUE TITLE
Default size problem.

### ISSUE THREAD

**Issue by Tahiche** [saribe/eModal#73]
If setting a default size 
`
eModal.setEModalOptions({
                size: 'lg'
        });
`
You´d expect to get the same modal size from this:
`eModal.ajax('./modal_load.php','Modal Title');`
and this...
`
eModal.ajax({
url:'./modal_load.php',
size: 'lg'
})
`
I would expect the same markup in both cases, and the same css classes, styles, etc. But it´s not the case.
Here´s the code that builds the size markup (_setup() function):
```
/#region change size
            $ref.find(MODAL_DIALOG)
                .removeClass('modal-sm modal-lg modal-xl')
                .addClass(params.size ? 'modal-' + params.size :  defaultSettings.size);
            //#endregion
```
This renders class "modal-dialog modal-lg" when specifing size (second case) but "modal-dialog lg" when using default values. 
I think it makes sense for it to return the same classes regardless. If size is passed as a parameter or if it´s using default values. Otherwise we´d have to duplicate styles, etc... 
Changing that line to:
`.addClass(params.size ? 'modal-' + params.size : 'modal-' + defaultSettings.size);`
Ensures we obtain the same markup using explicit or default size.
Un less i´m missing something i don´t see the point of having different classes...

**Comment by saribe** [comment]
Nice catch will fix it... thanks for reporting and investigating
