### ISSUE TITLE
Controlling the size of the iframe

### ISSUE THREAD

**Issue by Northshoot** [saribe/eModal#78]
Hey

Thanks for a great script!

What would be the advisable way to control the size of the iframe modal more gradually?

**Comment by saribe** [comment]
We included an extra size that is not specified on the bootstrap interface (XL)

https://getbootstrap.com/docs/4.0/components/modal/#optional-sizes

We don't have any easy way to do it.. however we can always manipulate the dom if needed.

const { then, catch, element } = eModal.ifram(args);

element.find(SELECTOR) => and change it...
