### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by karthik-code** [saribe/eModal#8]
I am receiving an error in browser console as below :
> eModal.min.js.map:2 Uncaught SyntaxError: Unexpected token 

But everything is working fine. 
How to fix this issue?

**Comment by saribe** [comment]
Are you using Google Chrome?
please check this link:
http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found

Disable *.map request in browser, for debug, use non minified version of
eModal

Is releated whit it?

Best



*Samuel Ribeiro Pinto*


2015-05-28 16:39 GMT+01:00 Karthikeyan <notifications@github.com>:

**Comment by karthik-code** [comment]
Chrome & Firefox both logs the above error in console.
It seems not necessary to include *.map file in production site. I removed it.
Thanks.
