### ISSUE TITLE
Bootstrap 4 issue

### ISSUE THREAD

**Issue by joshuajott** [saribe/eModal#82]
Have found an issue where in bootstrap 4 you receive the following error. 

jquery-3.3.1.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (jquery-3.3.1.min.js:2)
    at Object.iframe (eModelView.js:452)
    at Object.Open (frm_mass_email.aspx?from_idno=1&type=top&idno=1&sn=y&pg=1:491)
    at <anonymous>:1:18

Which is triggered by the:  

 var message = $(html).load(iframeReady);

This is bootstrap 4 and the Jquery 3.3.1.     Same code works fine though over in Bootstrap 3.x.x

**Comment by saribe** [comment]
jQuery v >= 3.0.0 has added in last version 1.2.66.

Please give a try and let us know.

PS: Bootstrap 4 was not tested yet. Will implement asap
