### ISSUE TITLE
After loading ajax modal, jquery ui .button() function not working

### ISSUE THREAD

**Issue by karthik-code** [saribe/eModal#9]
After loading ajax modal all other jquery functions which uses the jquery ui .button() function not working. 
i.e., functions which has the following code are not working. 
```javascript
 $btn.button('loading');
```
Console logs the following error : 
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to  the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
> Uncaught TypeError: $(...).button is not a function

**Comment by saribe** [comment]
I can't repro this, can you provide an example in codepen or something alike?

do you have <script async src="..."/> in your ajax template target?

**Comment by karthik-code** [comment]
I found that the loaded content from URL via ajax modal contains Jquery which causes issue.
 i.e., loading the jquery script again on the modal content produces the above error. 

Thanks for quicker response and making this awesome script.
